# render.yaml
services:
  - type: web
    name: pedidos-backend
    env: python
    region: frankfurt
    buildCommand: ./build.sh
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        fromDatabase:
          name: pedidos-db
          property: connectionString
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.console.EmailBackend"

databases:
  - name: pedidos-db
    databaseName: secure_messaging_k977
    user: admin
    plan: free
