# Generated by Django 6.0 on 2026-04-30 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('medicos', 'Médicos'), ('outros', 'Outros'), ('documentos', 'Documentos'), ('escola', 'Sugerido pela Escola'), ('coletiva', 'Saída Coletiva')], max_length=20)),
                ('motivo', models.TextField()),
                ('data_saida', models.DateTimeField()),
                ('hora_saida', models.TimeField()),
                ('estado', models.CharField(choices=[('PENDENTE_DITE', 'Verde - Pendente DITE'), ('PENDENTE_DIRECAO', 'Amarelo - Pendente Direção'), ('PENDENTE_ADMIN', 'Vermelho - Pendente Admin'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE_DITE', max_length=20)),
                ('responsavel_atual', models.CharField(choices=[('DITE', 'DITE'), ('DIRECAO', 'Direção'), ('ADMIN', 'Admin')], default='DITE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100)),
                ('de_responsavel', models.CharField(max_length=20)),
                ('para_responsavel', models.CharField(max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'historico_pedidos',
                'ordering': ['-data'],
            },
        ),
    ]
