# Generated by Django 5.2.13 on 2026-05-02 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicopedido',
            options={'ordering': ['-data'], 'verbose_name': 'Histórico', 'verbose_name_plural': 'Históricos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RemoveField(
            model_name='historicopedido',
            name='de_responsavel',
        ),
        migrations.RemoveField(
            model_name='historicopedido',
            name='para_responsavel',
        ),
        migrations.AddField(
            model_name='historicopedido',
            name='de_estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicopedido',
            name='para_estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicopedido',
            name='role_usuario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_decisao_admin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_decisao_direcao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_decisao_dite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='decisao_admin',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('PENDENTE', 'Pendente')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='decisao_direcao',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('PENDENTE', 'Pendente')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='decisao_dite',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('PENDENTE', 'Pendente')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicopedido',
            name='acao',
            field=models.CharField(choices=[('CRIADO', 'Pedido Criado'), ('APROVADO_DITE', 'Aprovado pelo DITE'), ('REJEITADO_DITE', 'Rejeitado pelo DITE'), ('PASSADO_DIRECAO', 'Encaminhado para Direção'), ('APROVADO_DIRECAO', 'Aprovado pela Direção'), ('REJEITADO_DIRECAO', 'Rejeitado pela Direção'), ('PASSADO_ADMIN', 'Encaminhado para Admin'), ('APROVADO_ADMIN', 'Aprovado pelo Admin'), ('REJEITADO_ADMIN', 'Rejeitado pelo Admin'), ('FINALIZADO', 'Processo Finalizado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historicopedido',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicopedido',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_historico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDENTE_DITE', '🟢 Pendente DITE'), ('PENDENTE_DIRECAO', '🟡 Pendente Direção'), ('PENDENTE_ADMIN', '🔴 Pendente Admin'), ('APROVADO', '✅ Aprovado'), ('REJEITADO', '❌ Rejeitado')], default='PENDENTE_DITE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='responsavel_atual',
            field=models.CharField(default='DITE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('medicos', '🏥 Médicos'), ('outros', '📋 Outros'), ('documentos', '📄 Documentos'), ('escola', '🏫 Sugerido pela Escola'), ('coletiva', '👥 Saída Coletiva')], max_length=20),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOVO_PEDIDO', 'Novo Pedido'), ('PEDIDO_APROVADO', 'Pedido Aprovado'), ('PEDIDO_REJEITADO', 'Pedido Rejeitado'), ('PEDIDO_ENCAMINHADO', 'Pedido Encaminhado'), ('DECISAO_NECESSARIA', 'Decisão Necessária')], max_length=30)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'db_table': 'notificacoes',
                'ordering': ['-data'],
            },
        ),
    ]
