# Generated by Django 5.2.13 on 2026-05-03 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_historicopedido_options_alter_pedido_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacao',
            options={'ordering': ['-data']},
        ),
        migrations.AlterField(
            model_name='historicopedido',
            name='acao',
            field=models.CharField(choices=[('CRIADO', 'Pedido Criado'), ('APROVADO_DITE', 'Aprovado pelo DITE'), ('REJEITADO_DITE', 'Rejeitado pelo DITE'), ('PASSADO_DIRECAO', 'Encaminhado para Direção'), ('APROVADO_DIRECAO', 'Aprovado pela Direção'), ('REJEITADO_DIRECAO', 'Rejeitado pela Direção'), ('PASSADO_ADMIN', 'Encaminhado para Admin'), ('APROVADO_ADMIN', 'Aprovado pelo Admin'), ('REJEITADO_ADMIN', 'Rejeitado pelo Admin'), ('EDITADO', 'Pedido Editado'), ('DELETADO', 'Pedido Deletado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('NOVO_PEDIDO', 'Novo Pedido'), ('PEDIDO_APROVADO', 'Pedido Aprovado'), ('PEDIDO_REJEITADO', 'Pedido Rejeitado'), ('PEDIDO_ENCAMINHADO', 'Pedido Encaminhado'), ('SISTEMA', 'Notificação do Sistema')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='decisao_admin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='decisao_direcao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='decisao_dite',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('dados', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'db_table': 'relatorios',
                'ordering': ['-created_at'],
            },
        ),
    ]
