# Generated by Django 5.2.13 on 2026-05-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_notificacao_options_alter_historicopedido_acao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicopedido',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='relatorio',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_decisao_administracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='decisao_administracao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicopedido',
            name='acao',
            field=models.CharField(choices=[('CRIADO', 'Pedido Criado'), ('APROVADO_DITE', 'Aprovado pelo DITE'), ('REJEITADO_DITE', 'Rejeitado pelo DITE'), ('PASSADO_DIRECAO', 'Encaminhado para Direção/Administração'), ('APROVADO_DIRECAO', 'Aprovado pela Direção'), ('REJEITADO_DIRECAO', 'Rejeitado pela Direção'), ('APROVADO_ADMINISTRACAO', 'Aprovado pela Administração'), ('REJEITADO_ADMINISTRACAO', 'Rejeitado pela Administração'), ('PASSADO_ADMIN', 'Encaminhado para Admin'), ('APROVADO_ADMIN', 'Aprovado pelo Admin'), ('REJEITADO_ADMIN', 'Rejeitado pelo Admin'), ('EDITADO', 'Pedido Editado'), ('DELETADO', 'Pedido Deletado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDENTE_DITE', '🟢 Pendente DITE'), ('PENDENTE_DIRECAO', '🟡 Pendente Direção/Administração'), ('PENDENTE_ADMIN', '🔴 Pendente Admin'), ('APROVADO', '✅ Aprovado'), ('REJEITADO', '❌ Rejeitado')], default='PENDENTE_DITE', max_length=20),
        ),
    ]
