# Generated by Django 5.2.13 on 2026-05-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_historicopedido_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicopedido',
            options={'ordering': ['-data'], 'verbose_name': 'Histórico', 'verbose_name_plural': 'Históricos'},
        ),
        migrations.AlterModelOptions(
            name='notificacao',
            options={'ordering': ['-data'], 'verbose_name': 'Notificação', 'verbose_name_plural': 'Notificações'},
        ),
        migrations.AlterModelOptions(
            name='relatorio',
            options={'ordering': ['-created_at'], 'verbose_name': 'Relatório', 'verbose_name_plural': 'Relatórios'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='responsavel_atual',
            field=models.CharField(default='DITE', max_length=50),
        ),
    ]
