# Generated by Django 6.0 on 2026-05-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_historicopedido_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicopedido',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='notificacao',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='relatorio',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='responsavel_atual',
            field=models.CharField(default='DITE', max_length=20),
        ),
    ]
