# Generated by Django 6.0 on 2026-05-04 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_historicopedido_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='alterado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datas_alteradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='atrasado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_saida_confirmada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_volta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_volta_confirmada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='hora_retorno_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='hora_saida_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_alteracao_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacao_seguranca',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tempo_atraso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicopedido',
            name='acao',
            field=models.CharField(choices=[('CRIADO', 'Pedido Criado'), ('APROVADO_DITE', 'Aprovado pelo DITE'), ('REJEITADO_DITE', 'Rejeitado pelo DITE'), ('PASSADO_DIRECAO', 'Encaminhado para Direção/Administração'), ('APROVADO_DIRECAO', 'Aprovado pela Direção'), ('REJEITADO_DIRECAO', 'Rejeitado pela Direção'), ('APROVADO_ADMINISTRACAO', 'Aprovado pela Administração'), ('REJEITADO_ADMINISTRACAO', 'Rejeitado pela Administração'), ('PASSADO_ADMIN', 'Encaminhado para Admin'), ('APROVADO_ADMIN', 'Aprovado pelo Admin'), ('REJEITADO_ADMIN', 'Rejeitado pelo Admin'), ('EDITADO', 'Pedido Editado'), ('DELETADO', 'Pedido Deletado'), ('INICIAR_ANDAMENTO', 'Saída Iniciada'), ('FINALIZAR_SAIDA', 'Saída Finalizada'), ('DATAS_ALTERADAS', 'Datas Alteradas')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('NOVO_PEDIDO', 'Novo Pedido'), ('PEDIDO_APROVADO', 'Pedido Aprovado'), ('PEDIDO_REJEITADO', 'Pedido Rejeitado'), ('PEDIDO_ENCAMINHADO', 'Pedido Encaminhado'), ('DATAS_ALTERADAS', 'Datas Alteradas'), ('SAIDA_INICIADA', 'Saída Iniciada'), ('SAIDA_FINALIZADA', 'Saída Finalizada'), ('ATRASO', 'Atraso Registrado'), ('SISTEMA', 'Notificação do Sistema')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDENTE_DITE', '🟢 Pendente DITE'), ('PENDENTE_DIRECAO', '🟡 Pendente Direção/Administração'), ('PENDENTE_ADMIN', '🔴 Pendente Admin'), ('APROVADO', '✅ Aprovado'), ('REJEITADO', '❌ Rejeitado'), ('EM_ANDAMENTO', '🚶 Em Andamento'), ('FINALIZADO', '🏁 Finalizado')], default='PENDENTE_DITE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='hora_saida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
