# Generated by Django 5.2.13 on 2026-05-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_servermonitor_user_can_login_user_can_register_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servermonitor',
            options={'ordering': ['-checked_at']},
        ),
        migrations.AlterModelOptions(
            name='systemlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ADMINISTRACAO', 'Administração'), ('DIRECAO', 'Direção'), ('DITE', 'DITE'), ('ESTUDANTE', 'Estudante')], default='ESTUDANTE', max_length=20),
        ),
    ]
