# Generated by Django 5.2.13 on 2026-05-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_servermonitor_options_alter_systemlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servermonitor',
            options={'ordering': ['-checked_at'], 'verbose_name': 'Monitor do Servidor', 'verbose_name_plural': 'Monitoramento do Servidor'},
        ),
        migrations.AlterModelOptions(
            name='systemlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log do Sistema', 'verbose_name_plural': 'Logs do Sistema'},
        ),
    ]
