# Generated by Django 6.0 on 2026-05-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_servermonitor_options_alter_systemlog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('DIRECAO', 'Direção'), ('DITE', 'DITE'), ('ESTUDANTE', 'Estudante')], default='ESTUDANTE', max_length=20),
        ),
    ]
