# Generated by Django 6.0 on 2026-05-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('DIRECAO', 'Direção'), ('DITE', 'DITE'), ('ESTUDANTE', 'Estudante'), ('ADMINISTRACAO', 'Administração'), ('SEGURANCA', 'Segurança')], default='ESTUDANTE', max_length=20),
        ),
    ]
